### ISSUE TITLE
does not work with Rails 4.2.1

### ISSUE THREAD

**Issue by ippeiukai** [willbryant/columns_on_demand#2]
```
ArgumentError: wrong number of arguments (1 for 2)
	from /__MY_HOME__/.rvm/gems/ruby-2.2.1/gems/columns_on_demand-4.2.0/lib/columns_on_demand.rb:165:in `build_select_with_columns_on_demand'
	from /__MY_HOME__/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/relation/query_methods.rb:878:in `build_arel'
	from /__MY_HOME__/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/relation/query_methods.rb:858:in `arel'
	from /__MY_HOME__/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/relation.rb:638:in `exec_queries'
```

Probably this:
https://github.com/rails/rails/commit/0662db16ade8f9ca40f4feda760472c9c7485db2

**Comment by ippeiukai** [comment]
and this too:
https://github.com/rails/rails/commit/f888fad4db6d6956b675ca0441baa5aa63edae32

**Comment by ippeiukai** [comment]
ended up with a lengthy monkey patch...
https://gist.github.com/ippeiukai/38cdc7b3c38fd578bc08
